// Code generated by MockGen. DO NOT EDIT.
// Source: misc.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMiscDatastore is a mock of MiscDatastore interface.
type MockMiscDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockMiscDatastoreMockRecorder
}

// MockMiscDatastoreMockRecorder is the mock recorder for MockMiscDatastore.
type MockMiscDatastoreMockRecorder struct {
	mock *MockMiscDatastore
}

// NewMockMiscDatastore creates a new mock instance.
func NewMockMiscDatastore(ctrl *gomock.Controller) *MockMiscDatastore {
	mock := &MockMiscDatastore{ctrl: ctrl}
	mock.recorder = &MockMiscDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiscDatastore) EXPECT() *MockMiscDatastoreMockRecorder {
	return m.recorder
}

// CreateOrUpdateKeyValue mocks base method.
func (m *MockMiscDatastore) CreateOrUpdateKeyValue(key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateKeyValue", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateKeyValue indicates an expected call of CreateOrUpdateKeyValue.
func (mr *MockMiscDatastoreMockRecorder) CreateOrUpdateKeyValue(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateKeyValue", reflect.TypeOf((*MockMiscDatastore)(nil).CreateOrUpdateKeyValue), key, value)
}

// DeleteValueByKeys mocks base method.
func (m *MockMiscDatastore) DeleteValueByKeys(keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteValueByKeys", keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteValueByKeys indicates an expected call of DeleteValueByKeys.
func (mr *MockMiscDatastoreMockRecorder) DeleteValueByKeys(keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteValueByKeys", reflect.TypeOf((*MockMiscDatastore)(nil).DeleteValueByKeys), keys)
}

// GetValue mocks base method.
func (m *MockMiscDatastore) GetValue(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue.
func (mr *MockMiscDatastoreMockRecorder) GetValue(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockMiscDatastore)(nil).GetValue), key)
}
